# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad2b4ca329fe667e6b397b8e1a30c8bd799d6aadf7f39695cd7576a76253ab73e0badf8ab05e9f6f1b113ab3074b16a65001d95d12d00ce42f3cd8661bf5cb06

test:
  secret_key_base: f82bffcd1e2d985a6a53c60843fdf06a5f3c168a9f7b27f690e1fd73be4521c8e3ef0786efaa97d71bce895aff6c4f43bf899368e44333bde1da47e0ecf60949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
